##############################
# DB #

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/fsc_home?useSSL=false
spring.datasource.username=root


#remote
spring.datasource.password=

#windows
#spring.datasource.password=password


spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql: true




##############################
# server #

server.port=8088
#server.http.port=8080
#server.ssl.enabled=true
